name: peer_app
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.1.1

  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  flutter_dio_http_cache: ^0.3.0
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  intl: ^0.19.0
  fl_chart: ^0.66.2
  flutter_launcher_icons: ^0.13.1

  graphql_flutter: ^5.1.0
  fluttertoast: ^8.2.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  carousel_slider: ^5.0.0
  video_player: ^2.8.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/peer_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/

dependency_overrides:
  win32: ^5.5.4  # Choose a version compatible with your project